language: "zh"
pipeline: 
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  epochs: 300
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: FormPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: action_repeate
