# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
importers:
  # Please place FAQImporter before other importers
  - name: ngchat_plugins.importers.faq_importer.FAQImporter
    faq_paths:
      - data/en_faq_sample.csv
    synonym_paths:
      - data/en_synonym_sample.csv
    augment_with_synonyms: false # recommended if you have synonyms and will use ElasticSelector with BERT, otherwise set to false
    timezone: Asia/Taipei # timezone used for dates in your faq file. Expressed as TZ database name. E.g. Seattle is "America/Los_Angeles".
  - name: RasaFileImporter

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 30
  - name: EntitySynonymMapper
  - name: ngchat_plugins.nlu.selectors.elastic_selector.ElasticSelector
    retrieval_intent: faq
    batch_size: 2048
    es_indexing:
      analyzer: standard
      host: quickstart-es-http.default.svc.cluster.local
      port: 9200
      index_name: linux_faq
      login: elastic
      secret: 73K7N2SQ4Yw2rr6L2q87yqEu # we need a way to read this from env
    bert_client:
      enabled: true
      host: bert-as-service
      port: 5555 # port for pushing data from client to server
      port_out: 5556 # port for publishing results from server to client
    eval:
      metric: map # options: map, mrr
      N: 1 # recommended options: 1, 3

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
